# Spring properties
spring:
  application:
    name: CloudApiTwo  # Identify this application
  cloud:
    config:
      uri: http://localhost:8004
  boot:
    #Spring boot admin settings
    admin:
#      url: http://localhost:2223
      routes:
        endpoints: env,metrics,trace,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,docs
        #Timeintervalin ms to update the status of App
      monitor:
        perio: 10000
        #LifeTime of App status in ms.
        status-lifetime: 10000
        #Connection Timeout in ms when App's status and info
        connect-timeout: 2000
        #Read Timeout in ms when App's status and info
        read-timeout: 5000
      metadata-keys-to-sanitize: .password$,.*secret$,.*key$,.$token$,.credentials.,.*vcap_services$
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2221/eureka/
  instance:
    hostname: ${spring.cloud.client.hostname}
##INFRA_ADMIN Settings
project:
  name: spring-cloud-api-two
  artifactId: spring-cloud-api-two
  description: spring-cloud-api-two
info:
  app:
    encoding: Encoding - UTF-8
  java:
    source: Source - java ver
    target: Instance1 - Java ver
  spring:
    profiles: ${spring.profiles.active:default}
  build:
    name: ${project.name}
    artifact: ${project.artifactId}
    description: ${project.description}

management:     # If you set off security...
  security:
    enabled: false

datasource:
  portal:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.68.46.219:3306/testdb
    username: testuser
    password: 'testuser'

jpa:
  database: mysql
  show-sql: true
  hibernate:
    ddl-auto: none
    naming:
      strategy: org.hibernate.dialect.MySQL5Dialect
  generate-ddl: false
